
name: 'Test Actions'
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: build docs
    steps:

    - name: Terraform Docs Build
      uses: lukegriffith/tf-config-docs@v0.0.2-alpha
