
name: 'Test Actions'
on: [push]

jobs:
  main:
    name: build docs
    runs-on: ubuntu-latest
    if: github.repository_owner == 'lukegriffith'
    steps:
    - uses: actions/checkout@v2
    - name: Terraform Docs Build
      uses: lukegriffith/tf-config-docs@alpha-v0.0.5
      with:
        data-output-path: ./docs
