
name: 'Test Actions'
on: [push]

jobs:
  main:
    name: build docs
    runs-on: ubuntu-latest
        if: github.repository_owner == 'lukegriffith'
    steps:

    - name: Terraform Docs Build
      uses: lukegriffith/tf-config-docs@v0.0.2-alpha
